project:
  type: book
  output-dir: docs

book:
  title: "Applied Programming for Geosciences"
  subtitle: "From Data Cleaning to Publishing"
  author: "Maximilian Nölscher"
  date: "3.2.2023"
  chapters:
    - index.qmd
    - intro.qmd
    - rbasics.qmd
    - data.qmd
    - analysis.qmd
    - visualization.qmd
    - manuscriptwriting.qmd
    - references.qmd
  repo-url: https://github.com/MxNl/applied_programming_for_geoscience_book
  repo-actions: [edit]
  downloads: [pdf, epub]

comments:
  hypothesis: true

css: style.css

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: images/logo.svg

editor: visual

